# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more supported hooks
# See also: https://pypi.org/project/pre-commit-hooks/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
#  - repo: https://github.com/jumanjihouse/pre-commit-hooks
#    sha: 1.11.0
#    hooks:
#      - id: markdownlint # Configure in .mdlrc
#  - repo: https://github.com/psf/black
#    rev: stable
#    hooks:
#      - id: black
#        language_version: python3.7
#  - repo: https://github.com/pre-commit/mirrors-pylint
#    rev: v2.4.3  # Use the sha / tag you want to point at
#    hooks:
#      - id: pylint
